### PR TITLE
Removed control menu in shex simple tool

### PR DESCRIPTION
**Pull request by rosalieper**
The control menu was removed and replaced by the about link as a button
see: https://phabricator.wikimedia.org/T221604

### CODE REVIEW

**Comment by micgro42** [comment]
It looks like there is a duplicate id: both on the button and on the new div inside of that button.

Also, the about text doesn't show when I click the about button.

**Comment by rosalieper** [comment]
https://github.com/shexSpec/shex.js/pull/49

**Comment by ericprud** [comment]
Should this PR be deleted as the conversation has moved to https://github.com/shexSpec/shex.js/pull/49 ?

**Comment by rosalieper** [comment]
Yes, I think so.

**Pull request closed without merging**
