### PR TITLE
Remove control menu in shex simple tool

### PR DESCRIPTION
**Pull request by rosalieper**
The control menu at the top of the page was removed it and replaced with just the about dialog.
Bug: T221604

### CODE REVIEW

**Comment by ericprud** [comment]
Did https://github.com/shexSpec/shex.js/commit/efa4c32c199bb8565a68bd2cd4b3bfbd6519f3c8 take care of this? I don't see a control menu in the [current interface](https://rawgit.com/shexSpec/shex.js/wikidata/packages/shex-webapp/doc/shex-simple.html) but I do [with `ui=full`](https://rawgit.com/shexSpec/shex.js/wikidata/packages/shex-webapp/doc/shex-simple.html?ui=full).

**Comment by rosalieper** [comment]
Actually this PR does not just remove the control menu but replaces it with an about button that was previously in the menu. I think ui=full had removed the menu completely including the `about` option?

**Comment by ericprud** [comment]
It did indeed. Is there much value to the about button? I guess it could get people to pitch in...

**Comment by lydiapintscher** [comment]
Yeah I didn't want us to hide where this was coming from. But if you don't mind then I'm ok with removing it.

**Comment by ericprud** [comment]
i put made some other interface dependent on a `ui=full` query parameter. i could do the same to hide the control menu.

**Comment by rosalieper** [comment]
closing it since ui=full already satisfy that. :+1:

**Pull request closed without merging**
