### PR TITLE
Rename and remove query input tabs in shex simple tool

### PR DESCRIPTION
**Pull request by rosalieper**
Query Map Renamed to Query
    Fixed Map Renamed to Entities to check
Query Map Editor tab is removed

Bug: T221606

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
I think this change should only happen when the `textMapIsSparqlQuery` URL parameter is set – the default behavior of the tool should be unchanged. (After all, by default the first tab doesn’t specify a query.)

**Comment by rosalieper** [comment]
> I think this change should only happen when the `textMapIsSparqlQuery` URL parameter is set – the default behavior of the tool should be unchanged. (After all, by default the first tab doesn’t specify a query.)

Ooh! I see, It makes sense

**Comment by rosalieper** [comment]
> I think this change should only happen when the `textMapIsSparqlQuery` URL parameter is set – the default behavior of the tool should be unchanged. (After all, by default the first tab doesn’t specify a query.)

How can I get the url please? I see it being used in the packages/shex-webapp/doc/shex-simple.js file, 
but it seems there is no function that returns it and I can't trace where it was defined or declared. Maybe am checking the wrong file?

**Comment by lucaswerkmeister** [comment]
I think you can implement this in the `loadSearchParameters` function – there’s already a condition in there for the `textMapIsSparqlQuery` parameter, you can update the tabs there.

**Comment by rosalieper** [comment]
Hi @ericprud , Please Should I conclude from this merge that I should stop work on this task?

**Pull request merged**
