### PR TITLE
Roundtrip ShEx translation script with test files

### PR DESCRIPTION
**Pull request by glenna-m**

### CODE REVIEW

**Comment by ericprud** [comment]
I've rearranged the extensions to accommodate extension-specific tools like ```bin/roundtrip-translation.sh```.
I propose to ```git mv bin/roundtrip-translation.sh extensions/shex:Map/util/roundtrip-translation.sh``` as I can imagine lots of ShExMap tools and scripts.
I changed ```./output``` to ```test/work``` by changing ```test/roundtrip-translation-test.js``` but never finished.
The scripts take 12s to test, up from 2s which I think is an acceptable limit for a pre-commit script.

**Comment by glenna-m** [comment]
Putting roundtrip-translation.sh in test is fine - testing is the primary use case.  My code has not been using /tmp for the files I generated - it was using ./output, but I think it's fine to put that under test/work since you moved the script over.

**Comment by glenna-m** [comment]
You will see that the round trip script is using rdf-to-json.  You were asking in a related email why I put that into ShEx - this is the reason why.  My assumption was that JSON-LD to RDF and back was a common use case for ShEx.  If this is incorrect, then perhaps it should be moved.  You will recall we discussed this over skype at one point and I thought we had agreed to put that tool into bin because we wanted people to find it and know it was there to use.  Do you see it differently now?

**Comment by glenna-m** [comment]
Yes, sed -i is a Mac-ism.  It is required on that platform.  I did not think it was a problem for Linux, but it sounds like it is.  Should be pretty easy to add a check for whether we are running on a Mac or not.  I can do this if you would like me to.  In my latest version of these files (not in this PR, I actually only use it once - for the CLOSED case, and I was thinking about removing it and requiring the back translation since I find I am having to do a separate back translation file anyway, so I can use the constant var file values.

**Comment by glenna-m** [comment]
I had planned to use Chai-as-promised but found I did not need it.  We can remove it until such a time as there is need.

**Comment by glenna-m** [comment]
Regarding the length of time to run the tests, I agree it's slow, and probably doesn't need to be run all the time.  That's why it's in its own test file.

**Comment by glenna-m** [comment]
I'm a little surprised you had to un-DOS any files, since I have been using tools like vi and emacs, and those kinds of problems do not usually occur on the Mac anyway, since it is using a Mach kernel, afterall.   There is a git config option that will force Unix-only LF files on checkin documented here: https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration.  I have set git config --global core.autocrlf input so hopefully that will help ensure we do not see it again for any reason.

**Pull request closed without merging**
