### PR TITLE
Remove Control menu and replace with About button

### PR DESCRIPTION
**Pull request by rosalieper**

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
I’m not sure when or where the menu should be removed, to be honest. Should it be removed on the master branch, on the wikidata branch (as this PR does), or perhaps only conditionally on the wikidata branch, e. g. based on some URL parameter? I’ve never used it myself, but perhaps it’s useful for others.

Also, the second commit has tons of whitespace changes that probably shouldn’t happen, though I’m not sure how easy it is to remove them :/

**Comment by rosalieper** [comment]
OMG, no idea where the spaces came from. Sorry, will fix

**Comment by ericprud** [comment]
Some folks (myself included) use control menu features on wikidata, in particular, the slurp mode, which makes a local copy of the data visited by the validation

**Comment by lydiapintscher** [comment]
I think for now let's remove it on the Wikidata branch and see if there is enough demand to add particular menu items back when the editors are using it.

**Pull request closed without merging**
